// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Pomo struct {
	ID          int32              `json:"id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	IsCompleted bool               `json:"is_completed"`
	IsRunning   bool               `json:"is_running"`
	SubtaskID   int32              `json:"subtask_id"`
}

type PomoUser struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Pin      string `json:"pin"`
}

type Subtask struct {
	ID            int32              `json:"id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	PomosRequired int32              `json:"pomos_required"`
	TaskID        int32              `json:"task_id"`
}

type Task struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	PomoUserID  int32              `json:"pomo_user_id"`
}
