// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"
)

type Querier interface {
	CancelPomo(ctx context.Context, id int32) (Pomo, error)
	ChangePin(ctx context.Context, arg ChangePinParams) error
	CompletePomo(ctx context.Context, id int32) (Pomo, error)
	CompleteSubtask(ctx context.Context, id int32) (Subtask, error)
	CompleteTask(ctx context.Context, id int32) (Task, error)
	CreatePomo(ctx context.Context, subtaskID int32) (Pomo, error)
	CreateSubtask(ctx context.Context, arg CreateSubtaskParams) (Subtask, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteSubtask(ctx context.Context, id int32) error
	DeleteTask(ctx context.Context, id int32) error
	GetAllPomosOfSubTask(ctx context.Context, subtaskID int32) ([]Pomo, error)
	GetCompletedPomosOfSubTask(ctx context.Context, subtaskID int32) ([]Pomo, error)
	GetRunningPomoOfSubTask(ctx context.Context, subtaskID int32) (Pomo, error)
	GetSubtasksOfTask(ctx context.Context, taskID int32) ([]Subtask, error)
	GetTasksOfUser(ctx context.Context, pomoUserID int32) ([]Task, error)
}

var _ Querier = (*Queries)(nil)
